# Generated by Django 5.2.3 on 2025-07-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_bid', models.IntegerField()),
                ('item_description', models.CharField(max_length=1000)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='auctions.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
