# Generated by Django 4.2.23 on 2025-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_watchlist_user_alter_watchlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winning_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
