# Generated by Django 4.2.23 on 2026-04-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_videopost_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
