# Generated by Django 4.2.23 on 2026-06-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
