# Generated by Django 4.2.23 on 2026-06-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_conversation_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reshares', to='HomePage.videopost'),
        ),
    ]
